root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
rules:
  'vue/multi-word-component-names': 'off'
