root: true
env:
  browser: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions:
    - '.vue'
# plugins:
#   - '@typescript-eslint'
#   - 'vue'
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:@typescript-eslint/strict-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
rules:
  'vue/multi-word-component-names': 'off'
