name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'v2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'v2/.tool-versions'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn
    - run: yarn lint
